# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs

jobs:
  build:
    docker:
      - image: cimg/azure:2023.08 
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command:  
            npm install
            npm run build
      - run:
          name: Run SonarCloud analysis
          command: 
            export SONAR_PROJECT_KEY=tvasha-1
            export SONAR_ORGANIZATION=your-sonar-organization
            sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORGANIZATION
    

  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud

orbs:
      sonarcloud: sonarsource/sonarcloud@1.0.3

