# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs

jobs:
  build:
    docker:
      - image: cimg/azure:2023.08 
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command:  
            npm install
            npm run build
      - sonarcloud/scan

  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud

